### ISSUE TITLE
I've made the extension but the bot does not work

### ISSUE THREAD

**Issue by wewe7144** [Frizz925/gbf-autopilot#11]
I've made the extension and the bot extension light up. However, when I turn the bot on, nothing happens. Im guessing what happens is that I did something wrong somewhere because when I start the server using npm script, it returns a series of errors.

**Comment by Frizz925** [comment]
Post the log

**Comment by Frizz925** [comment]
Post the log

**Comment by joezhoucn** [comment]
You should return the error log here.
One question : Have you turn the language to english? If you keep the language Japanese, there will be some error when you start the server.

**Comment by serenotus** [comment]
Maybe the same problem. I'm also failed and here's my error log.
```
$ npm start

> gbf-autopilot@0.0.1 start XXXXX\gbf-autopilot
> cross-env NODE_ENV=production concurrently "node index.js" "python controller.py"

[0] extensions.js not found. Not loading extensions.
[1]  * Running on http://localhost:XXXXX/ (Press CTRL+C to quit)
[0] events.js:183
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: listen EADDRINUSE 127.0.0.1:49544
[0]     at Object._errnoException (util.js:1022:11)
[0]     at _exceptionWithHostPort (util.js:1044:20)
[0]     at Server.setupListenHandle [as _listen2] (net.js:1351:14)
[0]     at listenInCluster (net.js:1392:12)
[0]     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
[0]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
[0] node index.js exited with code 1
[0] 2018-01-18T05:53:06.873Z - debug: Socket  'XXXXX' started
[0] extensions.js not found. Not loading extensions.
[1] 127.0.0.1 - - [18/Jan/2018 13:53:06] "POST /start HTTP/1.1" 200 -
[0] 2018-01-18T05:53:06.878Z - info: Autopilot started.
[0] 2018-01-18T05:53:06.892Z - debug: Waiting element: .atx-lead-link
[0] 2018-01-18T05:53:06.896Z - debug: Checking element: .icon-supporter-type-1.unselected
[0] 2018-01-18T05:53:06.901Z - debug: Clicking element: .icon-supporter-type-1
[1] 127.0.0.1 - - [18/Jan/2018 13:53:06] "POST /click HTTP/1.1" 500 -
[0] 2018-01-18T05:53:06.909Z - info: AP potion used: 0
[0] 2018-01-18T05:53:06.909Z - error:  Error: Request failed with status code 500
[0]     at createError ( XXXXX\gbf-autopilot\node_modules\axios\lib\core\createError.js:16:15)
[0]     at settle ( XXXXX\gbf-autopilot\node_modules\axios\lib\core\settle.js:18:12)
[0]     at IncomingMessage.handleStreamEnd ( XXXXX\gbf-autopilot\node_modules\axios\lib\adapters\http.js:191:11)
[0]     at emitNone (events.js:111:20)
[0]     at IncomingMessage.emit (events.js:208:7)
[0]     at endReadableNT (_stream_readable.js:1055:12)
[0]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0] 2018-01-18T05:53:06.909Z - debug: Stopping socket ' XXXXX'
[1] 127.0.0.1 - - [18/Jan/2018 13:53:06] "POST /stop HTTP/1.1" 200 -
[0] 2018-01-18T05:53:06.914Z - info: Autopilot stopped.
```

**Comment by Frizz925** [comment]
Closed due to no response
