### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by srwgin** [Frizz925/gbf-autopilot#14]
now I test [EventMode]
1.only work with game.granbluefantasy.jp,not work with gbf.game.mbga.jp 
2.only work with english language,not work with japanese
3.poker bot not work right?
4.I found it can only click attack can not use skill,I think I need a EventRaidScript but how to write
should I just use this
https://github.com/Frizz925/gbf-autopilot-scenarios/blob/master/GuildWar.js

**Comment by srwgin** [comment]
I find the problem
the next button name is bnt-result
I do not know why log is cnt-result

**Comment by Frizz925** [comment]
1. idk how did you manage to use gbf.game.mbga.jp without UA spoofing, that site is for mobile-only so it won't be supported.
2. Is this the game or OS language? Last time I tested with the game Japanese language it worked just fine.
3. Poker bot is now a separate bot extension. You can read the guide in the wiki (recently updated) https://github.com/Frizz925/gbf-autopilot/wiki/Extensions
4. Old scenarios no longer work. Most of the scenarios scripting are now built-in to provide simpler setup. Battle scripting now uses Lua due to its coroutine capabilities and the API I've made for it making writing scripts much easier. The guide will be written later.

**Comment by srwgin** [comment]
the game language,OS language is chinese

**Comment by Frizz925** [comment]
Can you specify what kind of problems you ran into when using the game's Japanese language?

**Comment by srwgin** [comment]
log
[0] 2018-01-19T10:07:59.464Z - info: Waiting for supporter page...
[0] 2018-01-19T10:08:06.676Z - debug: Waiting element: .atx-lead-link
[0] 2018-01-19T10:08:07.707Z - debug: Checking element: .icon-supporter-type-undefined.unselected
[0] 2018-01-19T10:08:07.722Z - debug: Timeout: 50
[0] 2018-01-19T10:08:07.772Z - debug: Preferred summons: 0=Kaguya, 1=Rabbit
[0] 2018-01-19T10:08:08.027Z - debug: Selected summon: ルシフェル
[0] 2018-01-19T10:08:08.027Z - debug: Timeout: 50
[1] 127.0.0.1 - - [19/Jan/2018 18:08:08] "POST /click HTTP/1.1" 500 -
[0] 2018-01-19T10:08:08.106Z - info: AP potion used: 0
[0] 2018-01-19T10:08:08.112Z - info: Autopilot stopped.
[0] 2018-01-19T10:08:08.106Z - error:  Error: Request failed with status code 500
[0]     at createError (D:\game\gbf\gbfbackup\gbf-autopilot\node_modules\axios\lib\core\createError.js:16:15)
[0]     at settle (D:\game\gbf\gbfbackup\gbf-autopilot\node_modules\axios\lib\core\settle.js:18:12)
[0]     at IncomingMessage.handleStreamEnd (D:\game\gbf\gbfbackup\gbf-autopilot\node_modules\axios\lib\adapters\http.js:191:11)
[0]     at emitNone (events.js:111:20)
[0]     at IncomingMessage.emit (events.js:208:7)
[0]     at endReadableNT (_stream_readable.js:1055:12)
[0]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0] 2018-01-19T10:08:08.107Z - debug: Stopping socket 'Ciahyv1YjP9zUl0fAAAA'
[1] 127.0.0.1 - - [19/Jan/2018 18:08:08] "POST /stop HTTP/1.1" 200 -

**Comment by srwgin** [comment]
I also change something in config.ini
[General]
Language=jp
[Summons]
PreferredSummons=カグヤ
DefaultSummonAttributeTab=フリー
[EventMode]
NightmareModePreferredSummons=カグヤ
NightmareModeSummonAttributeTab=フリー

**Comment by Frizz925** [comment]
General.Language should be either en or jp. Closing this since the bot actually works with Japanese game language with proper configuration.

**Comment by srwgin** [comment]
I delete everything then reinstall
now it work with jp language

p.s.I saw "http://gbf.game.mbga.jp/*" in the manifest.json
then I thing it supported

**Comment by Frizz925** [comment]
The mobile site isn't supported yet. Supporting the mobile site means that I have to tweak the input controller and the chrome extension again for them to work properly.
