### ISSUE TITLE
Bug Reporting 

### ISSUE THREAD

**Issue by srwgin** [Frizz925/gbf-autopilot#15]
Summary
after kill monster it can not click next button

Branch
master

Commit hash
991ab1716c5b3b76fad1ee8e1024e1f75b84f28f

System information

OS: Windows 10 Pro 64-bit
Screen resolution: 1680x1050 @ 1.0x
Chrome version:   65.0.3298.4 (Official Build) (32-bit)
Node.js version: v8.9.4
Python version: 3.6.4

Configuration
[Server]
ListenerPort=49544
ProcessTimeoutInMs=60000
WorkerTimeoutInMs=1000
WaitAjaxTimeoutInMs=5000

[Controller]
ListenerPort=49545
MouseTween=easeInOutCubic

[Debug]
LogLevel=debug
LogToFile=false
LogToOutput=true
LogToFileDirectory=log
LogSocket=false
ThrowErrors=false
TrialBattleMode=false

[General]
Language=en
MaxNumActionRetries=3
MinWaitTimeInMsAfterRefresh=2000
TimeLimitInSeconds=3600
UseViramate=true
MaxNumPotionsToUse=999
UseFullElixirsWhenNoRemainingHalfAPPotions=false
UseFullElixirsFirst=false
TreasureId=
TreasureName=
TreasureTarget=

[Inputs]
DelayInMsBetweenMouseDownAndUp=40
RandomDelayInMsBetweenMouseDownAndUp=20
MouseSpeed=580
MouseSpeedBase=150
MouseScrollSpeed=250
ExitKeyCode=112
WaitTimeInMsBeforeClickInput=50

[PartySelection]
PreferredPartyGroup=1
PreferredPartyDeck=5
PreferredPartySet=A
PreferredNightmareModePartyGroup=1
PreferredNightmareModePartyDeck=1
PreferredNightmareModePartySet=A

[Summons]
PreferredSummons=Kaguya,Rabbit
DefaultSummonAttributeTab=Mise
RerollSummonWhenNoPreferredSummonWasFound=false

[Combat]
MinWaitTimeInMsAfterAttack=500
MinWaitTimeInMsAfterSummon=3000
MinWaitTimeInMsAfterAbility=2200
LuaScript=

[PokerMode]
Enabled=false
ChipAmount=1000
WinningRoundCap=5
WinningChipsCap=16000
WinningRateBase=0.75
WinningRateModifier=0.08

[EventMode]
Enabled=true
EventRaidUrl="http://game.granbluefantasy.jp/#quest/supporter/510031/5"
EventRaidScript=
NightmareModeUrl="http://game.granbluefantasy.jp/#quest/supporter/510051/5"
NightmareModeScript=
EventPageUrl="http://game.granbluefantasy.jp/#quest/extra"
NightmareModePreferredSummons=Kaguya
NightmareModeSummonAttributeTab=Mise
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
NightmareModeAvailableAtStart=false
WaitTimeInMsAfterEventPageIsLoaded=1000

[EventTreasureMode]
Enabled=false
EventTreasureUrl=
EventTreasureSoloUrl=
EventTreasureSoloModeScript=
EventTreasureRaidUrl=
EventTreasureRaidModeScript=
EventTreasureRaidItemRequiredCount=
NightmareModeUrl=
NightmareModeScript=
NightmareModePreferredSummons=
NightmareModeSummonAttributeTab=
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
NightmareModeAvailableAtStart=false

[RiseOfTheBeastsMode]
Enabled=false
RiseOfTheBeastsUrl=
RiseOfTheBeastsLuaScript=

[CoopSoloMode]
Enabled=false
LuaScript=

[CoopGuestMode]
Enabled=false
LuaScript=

[CustomizedScheduling]
Enabled=false
SchedulingLuaScript=

[DimensionalHalo]
RetreatWhenNoDimensionalHaloTransformation=true

Log
[0] 2018-01-19T08:14:36.125Z - debug: Socket 'i-Jma3mayLwbf-wGAAAD' started
[0] extensions.js not found. Not loading extensions.
[0] 2018-01-19T08:14:36.133Z - info: Autopilot started.
[0] 2018-01-19T08:14:36.133Z - info: Using 'Event' mode.
[1] 127.0.0.1 - - [19/Jan/2018 16:14:36] "POST /start HTTP/1.1" 200 -
[0] 2018-01-19T08:14:36.134Z - debug: Location change: http://game.granbluefantasy.jp/#quest/extra
[0] 2018-01-19T08:14:37.153Z - debug: Waiting element: .atx-lead-link
[0] 2018-01-19T08:14:37.161Z - debug: Checking element: .ico-difficulty-5,.ico-difficulty-8
[0] 2018-01-19T08:14:37.192Z - info: Using quest page: http://game.granbluefantasy.jp/#quest/supporter/510031/5
[0] 2018-01-19T08:14:37.193Z - debug: Ajax: GET /quest/user_action_point
[0] 2018-01-19T08:14:37.382Z - debug: Ajax: GET /quest/quest_data/510031/5
[0] 2018-01-19T08:14:37.527Z - debug: Ajax: POST /quest/set_return_point
[0] 2018-01-19T08:14:37.723Z - debug: Location change: http://game.granbluefantasy.jp/#quest/supporter/510031/5
[0] 2018-01-19T08:14:38.809Z - debug: Waiting element: .atx-lead-link
[0] 2018-01-19T08:14:38.819Z - debug: Checking element: .icon-supporter-type-undefined.unselected
[0] 2018-01-19T08:14:38.832Z - debug: Timeout: 50
[0] 2018-01-19T08:14:38.883Z - debug: Preferred summons: 0=Kaguya, 1=Rabbit
[0] 2018-01-19T08:14:38.896Z - debug: Selected summon: Kaguya
[0] 2018-01-19T08:14:38.896Z - debug: Timeout: 50
[1] 127.0.0.1 - - [19/Jan/2018 16:14:39] "POST /click HTTP/1.1" 200 -
[0] 2018-01-19T08:14:39.443Z - debug: Waiting element: .pop-deck.supporter
[0] 2018-01-19T08:14:46.680Z - debug: Timeout: 500
[0] 2018-01-19T08:14:47.180Z - debug: Using party group: 1
[0] 2018-01-19T08:14:47.180Z - debug: Clicking with condition: .btn-select-group.id-1
[0] 2018-01-19T08:14:47.180Z - debug: Checking element: .btn-select-group.id-1.selected
[0] 2018-01-19T08:14:47.188Z - debug: Timeout: 500
[0] 2018-01-19T08:14:47.689Z - debug: Using party deck: 5
[0] 2018-01-19T08:14:47.689Z - debug: Clicking with condition: .prt-deck-slider li:nth-child(5) > a
[0] 2018-01-19T08:14:47.689Z - debug: Checking element: .prt-deck-slider li:nth-child(5) > a.flex-active
[0] 2018-01-19T08:14:47.693Z - debug: Starting battle...
[0] 2018-01-19T08:14:47.694Z - debug: Clicking with condition: .btn-usual-ok
[0] 2018-01-19T08:14:47.694Z - debug: Clicking element: .btn-usual-ok
[1] 127.0.0.1 - - [19/Jan/2018 16:14:48] "POST /click HTTP/1.1" 200 -
[0] 2018-01-19T08:14:48.224Z - debug: Timeout: 1500
[0] 2018-01-19T08:14:49.376Z - debug: Waiting element: .btn-attack-start.display-on,.btn-result,.cnt-result
[0] 2018-01-19T08:14:54.511Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:14:54.678Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:14:54.773Z - debug: Checking element: .btn-result
[0] 2018-01-19T08:14:54.813Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:14:54.852Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:14:54.880Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:14:55.034Z - info: Attacking...
[0] 2018-01-19T08:14:55.035Z - debug: Waiting for action result
[0] 2018-01-19T08:14:55.036Z - debug: Clicking with condition: .btn-attack-start.display-on
[0] 2018-01-19T08:14:55.036Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:14:55.082Z - debug: Clicking element: .btn-attack-start.display-on
[1] 127.0.0.1 - - [19/Jan/2018 16:14:55] "POST /click HTTP/1.1" 200 -
[0] 2018-01-19T08:14:55.807Z - debug: Timeout: 1500
[0] 2018-01-19T08:14:56.283Z - debug: Action result received
[0] 2018-01-19T08:14:56.283Z - debug: Timeout: 500
[0] 2018-01-19T08:14:56.822Z - debug: Waiting element: .btn-attack-start.display-on,.btn-result,.cnt-result
[0] 2018-01-19T08:14:57.308Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:15:00.301Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:15:00.384Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:15:00.467Z - debug: Checking element: .btn-result
[0] 2018-01-19T08:15:00.512Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:15:00.531Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:15:00.551Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:15:00.628Z - info: Attacking...
[0] 2018-01-19T08:15:00.628Z - debug: Waiting for action result
[0] 2018-01-19T08:15:00.628Z - debug: Clicking with condition: .btn-attack-start.display-on
[0] 2018-01-19T08:15:00.628Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:15:00.648Z - debug: Clicking element: .btn-attack-start.display-on
[1] 127.0.0.1 - - [19/Jan/2018 16:15:01] "POST /click HTTP/1.1" 200 -
[0] 2018-01-19T08:15:01.239Z - debug: Timeout: 1500
[0] 2018-01-19T08:15:01.564Z - debug: Action result received
[0] 2018-01-19T08:15:01.564Z - debug: Timeout: 500
[0] 2018-01-19T08:15:02.087Z - debug: Waiting element: .btn-attack-start.display-on,.btn-result,.cnt-result
[0] 2018-01-19T08:15:02.741Z - debug: Checking element: .btn-attack-start.display-on
[0] 2018-01-19T08:15:03.239Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:15:03.309Z - debug: Viramate: type=getCombatState
[0] 2018-01-19T08:15:03.387Z - debug: Checking element: .btn-result
[0] 2018-01-19T08:15:03.401Z - debug: Timeout: 1500
[0] 2018-01-19T08:15:04.901Z - debug: Waiting element: .cnt-result
[0] 2018-01-19T08:16:04.903Z - info: AP potion used: 0
[0] 2018-01-19T08:16:04.903Z - error:  Error: Action element({"selector":".cnt-result","scroll":false,"retry":true}) timed out after 60000ms!
[0]     at Timeout._onTimeout (D:\game\gbf\gbfbackup\gbf-autopilot\server\dist\server.js:319:43)
[0]     at ontimeout (timers.js:475:11)
[0]     at tryOnTimeout (timers.js:310:5)
[0]     at Timer.listOnTimeout (timers.js:270:5)
[0] 2018-01-19T08:16:04.903Z - debug: Stopping socket 'i-Jma3mayLwbf-wGAAAD'
[1] 127.0.0.1 - - [19/Jan/2018 16:16:04] "POST /stop HTTP/1.1" 200 -
[0] 2018-01-19T08:16:04.910Z - info: Autopilot stopped.

**Comment by Frizz925** [comment]
Sounds like problem with the bot's core extension logic. Moved this to https://github.com/Frizz925/gbf-autopilot-core/issues/3
