### ISSUE TITLE
npm ERR

### ISSUE THREAD

**Issue by DJeffAlpha** [Frizz925/gbf-autopilot#24]
i have problem in npm ERR! code ELIFECYCLE and npm ERR! code EINTEGRITY

**Comment by Frizz925** [comment]
Post the complete log

**Comment by Yalzy** [comment]
i got same error like this 
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test:server' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'pretest:server', 'test:server', 'posttest:server' ]
5 info lifecycle gbf-autopilot@0.0.1~pretest:server: gbf-autopilot@0.0.1
6 info lifecycle gbf-autopilot@0.0.1~test:server: gbf-autopilot@0.0.1
7 verbose lifecycle gbf-autopilot@0.0.1~test:server: unsafe-perm in lifecycle true
8 verbose lifecycle gbf-autopilot@0.0.1~test:server: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Yalz\Desktop\gbf-autopilot\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Yalz\Desktop\gbf-autopilot\node_modules\.bin;C:\Users\Yalz\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Yalz\bin;C:\Python36\Scripts;C:\Python36;C:\Program Files (x86)\Python36-32\Scripts;C:\Program Files (x86)\Python36-32;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Microsoft MPI\Bin;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl\Win64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Python;C:\Python\Scripts;C:\Program Files (x86)\Common Files\Autodesk Shared;C:\Program Files (x86)\Autodesk\backburner;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Livestreamer;C:\Program Files (x86)\Streamlink\bin;C:\Program Files (x86)\Skype\Phone;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs;C:\Users\Yalz\AppData\Local\Microsoft\WindowsApps;C:\Users\Yalz\AppData\Roaming\Composer\vendor\bin;C:\Users\Yalz\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle gbf-autopilot@0.0.1~test:server: CWD: C:\Users\Yalz\Desktop\gbf-autopilot
10 silly lifecycle gbf-autopilot@0.0.1~test:server: Args: [ '/d /s /c', 'mocha test/server/**/*.js' ]
11 silly lifecycle gbf-autopilot@0.0.1~test:server: Returned: code: 1  signal: null
12 info lifecycle gbf-autopilot@0.0.1~test:server: Failed to exec test:server script
13 verbose stack Error: gbf-autopilot@0.0.1 test:server: `mocha test/server/**/*.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid gbf-autopilot@0.0.1
15 verbose cwd C:\Users\Yalz\Desktop\gbf-autopilot
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:server"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error gbf-autopilot@0.0.1 test:server: `mocha test/server/**/*.js`
22 error Exit status 1
23 error Failed at the gbf-autopilot@0.0.1 test:server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by Yalzy** [comment]
and when npm start got this


https://i.imgur.com/Z4lDS0V.png

**Comment by Frizz925** [comment]
Please don't use Git Bash on Windows when starting the server. Ctrl+C on the terminal won't kill the server process and causes EADDRINUSE error.

**Comment by Frizz925** [comment]
Closing this due to inactivity and lack of proper bug report.
