### ISSUE TITLE
stuck in Waiting element: .pop-deck.supporter,.pop-deck.supporter_raid

### ISSUE THREAD

**Issue by ssshooter** [Frizz925/gbf-autopilot#25]
### Summary
*stuck in Waiting element: .pop-deck.supporter,.pop-deck.supporter_raid*
$ [0] 2018-03-30T14:44:35.538Z - debug: Socket '2on7b9qaIcEkwvI7AAAA' started
[1] 127.0.0.1 - - [30/Mar/2018 22:44:35] "POST / HTTP/1.1" 200 -
[0] 2018-03-30T14:44:35.544Z - info: Autopilot started.
[0] 2018-03-30T14:44:35.560Z - debug: Waiting element: .atx-lead-link
[0] 2018-03-30T14:44:35.568Z - debug: Checking element: .icon-supporter-type-m.unselected
[0] 2018-03-30T14:44:35.575Z - debug: Timeout: 50
[0] 2018-03-30T14:44:35.625Z - debug: Preferred summons: 0=Kaguya, 1=Rabbit, 2=Bahamut
[0] 2018-03-30T14:44:35.782Z - info: Selected summon: Bahamut
[0] 2018-03-30T14:44:35.783Z - debug: Timeout: 50
[0] 2018-03-30T14:44:35.833Z - debug: Waiting element: .pop-deck.supporter,.pop-deck.supporter_rai                                                                                                                                                                             d
[1] 127.0.0.1 - - [30/Mar/2018 22:44:36] "POST / HTTP/1.1" 200 -
[0] 2018-03-30T14:44:36.338Z - debug: Timeout: 4000
[1] 127.0.0.1 - - [30/Mar/2018 22:44:40] "POST / HTTP/1.1" 200 -
[0] 2018-03-30T14:44:40.822Z - debug: Timeout: 4000
[1] 127.0.0.1 - - [30/Mar/2018 22:44:45] "POST / HTTP/1.1" 200 -
[0] 2018-03-30T14:44:45.331Z - debug: Timeout: 4000
[1] 127.0.0.1 - - [30/Mar/2018 22:44:49] "POST / HTTP/1.1" 200 -
[0] 2018-03-30T14:44:49.804Z - debug: Timeout: 4000
[0] 2018-03-30T14:44:51.402Z - debug: Got stop request from socket '2on7b9qaIcEkwvI7AAAA'
[0] 2018-03-30T14:44:51.402Z - debug: Stopping socket '2on7b9qaIcEkwvI7AAAA'
[1] 127.0.0.1 - - [30/Mar/2018 22:44:51] "POST / HTTP/1.1" 200 -
[0] 2018-03-30T14:44:51.406Z - info: Autopilot stopped.
[1] 127.0.0.1 - - [30/Mar/2018 22:44:53] "POST / HTTP/1.1" 200 -
[0] 2018-03-30T14:44:53.807Z - info: AP potion used: 0
[0] 2018-03-30T14:44:53.807Z - info: BP berry used: 0
[0] 2018-03-30T14:44:53.807Z - error:  Error: Controller not running!
[0]     at G:\gitit\gbf-autopilot\server\dist\lib\JsonRpcClient.js:45:31
[0]     at <anonymous>
[0]     at process._tickCallback (internal/process/next_tick.js:188:7)
[0] 2018-03-30T14:44:53.807Z - debug: Autopilot is not running!

### Branch
*master*

### Commit hash
*c4e600a7bdce061883979bffc6f400b2a067fe2f*

### Steps to reproduce
*npm start*
*start autopilot*

### Actual results
*cursor move abnormally*

### Game information
- *DMM*
- *English*

### System information
- *Win 10*
- *display scaling small*
- *Chrome version  65.0.3325.181*
- *Node.js version 8.10*
- *Python version 3.6*

### Configuration
```ini
[Server]
ListenerPort=49544
ProcessTimeoutInMs=60000
WorkerTimeoutInMs=500
WaitAjaxTimeoutInMs=5000
JsonRpcEndpoint=/jsonrpc

[Controller]
ListenerPort=49545
MouseTween=easeInOutCubic

[Debug]
LogLevel=debug
LogToFile=false
LogToOutput=true
LogToFileDirectory=log
LogSocket=false
ThrowErrors=false

[General]
Language=en
MaxNumActionRetries=2
MinWaitTimeInMsAfterRefresh=2000
TimeLimitInSeconds=5400
UseViramate=false
MaxNumPotionsToUse=999
UseFullElixirsWhenNoRemainingHalfAPPotions=false
UseFullElixirsFirst=false

[Summons]
PreferredSummons=Kaguya,Rabbit,Bahamut
DefaultSummonAttributeTab=Mise
RerollSummonWhenNoPreferredSummonWasFound=false

[Inputs]
DelayInMsBetweenMouseDownAndUp=40
RandomDelayInMsBetweenMouseDownAndUp=20
MouseSpeed=580
MouseSpeedBase=150
MouseScrollSpeed=250
ExitKeyCode=112
WaitTimeInMsBeforeClickInput=50

[Combat]
MinWaitTimeInMsAfterAttack=500
MinWaitTimeInMsAfterSummon=3000
MinWaitTimeInMsAfterAbility=2200

[Verification]
SummonVerifyEnabled=false
SummonVerifyTriggeredWhenSelectionIsLessThan=5

[DimensionalHalo]
RetreatWhenNoDimensionalHaloTransformation=true
```

![image](https://user-images.githubusercontent.com/13051472/38141744-329e9e06-346c-11e8-8d9d-9502d318bf7c.png)

**Comment by Frizz925** [comment]
```
DefaultSummonAttributeTab=Mise
```
?

**Comment by ssshooter** [comment]
so....comment this line ?

**Comment by Frizz925** [comment]
No, what is *Mise* value is this you're setting. The bot obviously doesn't recognize that value.

**Comment by ssshooter** [comment]
![image](https://user-images.githubusercontent.com/13051472/38158440-06c68342-34c7-11e8-8f7e-cbe97de15454.png)
Change `Mise` to `dark` , same problem 😭

**Comment by Frizz925** [comment]
See https://github.com/Frizz925/gbf-autopilot/issues/20

**Comment by ssshooter** [comment]
hmmm...what do 1.0x display scaling and Disabled global footer means ?

**Comment by ssshooter** [comment]
The cursor always move to the bottom of screen .

**Comment by Frizz925** [comment]
Try using mobage account

**Comment by ssshooter** [comment]
Thanks ! It works !
