### ISSUE TITLE
Apparently there was a missing module

### ISSUE THREAD

**Issue by sklin0er4** [Frizz925/gbf-autopilot#7]
[0] Client 'DzIfYbJz-VtdMUHgAAAC' connected!
[0] { Error: Cannot find module './scenarios/'
[0]     at Function.Module._resolveFilename (module.js:555:15)
[0]     at Function.resolve (internal/module.js:18:19)
[0]     at readScenario (C:\Users\<username>\Desktop\gbf-autopilot-master\server\server.js:14:28)
[0]     at Promise (C:\Users\<username>\Desktop\gbf-autopilot-master\server\server.js:27:24)
[0]     at new Promise (<anonymous>)
[0]     at Server (C:\Users\<username>\Desktop\gbf-autopilot-master\server\server.js:24:10)
[0]     at C:\Users\<username>\Desktop\gbf-autopilot-master\server\dist\server.js:75:23
[0]     at new Promise (<anonymous>)
[0]     at Server.configHandler (C:\Users\<username>\Desktop\gbf-autopilot-master\server\dist\server.js:74:14)
[0]     at Server.onConnect (C:\Users\<username>\Desktop\gbf-autopilot-master\server\dist\server.js:163:12) code: 'MODULE_NOT_FOUND' }
[0] Client 'DzIfYbJz-VtdMUHgAAAC' disconnected!

**Comment by sklin0er4** [comment]
Okay it works now(w/ the dangerous ver. but is there anyways to speed up clicking?)

**Comment by Frizz925** [comment]
Not yet. I'll consider it in the future.
